In [2]:
from fuzzycmeans import FCM
import numpy

In [3]:
X = numpy.array([[1, 1, 1], [1, 2, 2], [2, 2, 8], [0, 0, 5], [0, 0, 1]])
fcm = FCM(n_clusters=4, max_iter=1)
fcm.fit(X, [0, 0, 0, 1, 2])

In [4]:
Y = numpy.array([[1, 2, 3], [2, 2, 5], [3, 1, 2], [2, 1, 4], [6, 8,1]])
membership = fcm.predict(Y)

In [5]:
membership

array([[0.83628319, 0.0619469 , 0.0619469 , 0.03982301],
       [0.68512111, 0.19982699, 0.066609  , 0.04844291],
       [0.43671642, 0.13791045, 0.23820896, 0.18716418],
       [0.77777778, 0.12962963, 0.05555556, 0.03703704],
       [0.33692769, 0.20041388, 0.23248011, 0.23017832]])

In [6]:
import pandas

In [7]:
data = pandas.read_csv('data/iris.csv')

In [8]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [10]:
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [11]:
data_out = data['Species'].replace(['Iris-setosa', 
                                    'Iris-versicolor', 
                                    'Iris-virginica'],
                                   [0, 1, 2],
                                   inplace=False)

/tmp/ipykernel_22733/237811437.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_out = data['Species'].replace(['Iris-setosa',


In [12]:
data_out

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [13]:
data_list = []

for index, row in data.iterrows():
    data_list.append([row['SepalLengthCm'],
                       row['SepalWidthCm'],
                       row['PetalLengthCm'],
                       row['PetalWidthCm'], 
                      data_out[index]])

In [14]:
data_list

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.4, 3.7, 1.5, 0.2, 0],
 [4.8, 3.4, 1.6, 0.2, 0],
 [4.8, 3.0, 1.4, 0.1, 0],
 [4.3, 3.0, 1.1, 0.1, 0],
 [5.8, 4.0, 1.2, 0.2, 0],
 [5.7, 4.4, 1.5, 0.4, 0],
 [5.4, 3.9, 1.3, 0.4, 0],
 [5.1, 3.5, 1.4, 0.3, 0],
 [5.7, 3.8, 1.7, 0.3, 0],
 [5.1, 3.8, 1.5, 0.3, 0],
 [5.4, 3.4, 1.7, 0.2, 0],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.6, 3.6, 1.0, 0.2, 0],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.0, 3.0, 1.6, 0.2, 0],
 [5.0, 3.4, 1.6, 0.4, 0],
 [5.2, 3.5, 1.5, 0.2, 0],
 [5.2, 3.4, 1.4, 0.2, 0],
 [4.7, 3.2, 1.6, 0.2, 0],
 [4.8, 3.1, 1.6, 0.2, 0],
 [5.4, 3.4, 1.5, 0.4, 0],
 [5.2, 4.1, 1.5, 0.1, 0],
 [5.5, 4.2, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.0, 3.2, 1.2, 0.2, 0],
 [5.5, 3.5, 1.3, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.4, 3.0, 

In [15]:
import random
shuffle = True

In [16]:
if shuffle:
    for x in range(5):
        random.shuffle(data_list)

data_list

[[4.4, 2.9, 1.4, 0.2, 0],
 [6.4, 2.9, 4.3, 1.3, 1],
 [4.8, 3.1, 1.6, 0.2, 0],
 [6.3, 2.9, 5.6, 1.8, 2],
 [5.2, 3.5, 1.5, 0.2, 0],
 [6.1, 2.8, 4.7, 1.2, 1],
 [7.7, 3.0, 6.1, 2.3, 2],
 [6.2, 2.2, 4.5, 1.5, 1],
 [4.8, 3.4, 1.6, 0.2, 0],
 [6.3, 2.3, 4.4, 1.3, 1],
 [4.6, 3.1, 1.5, 0.2, 0],
 [6.2, 3.4, 5.4, 2.3, 2],
 [5.4, 3.7, 1.5, 0.2, 0],
 [6.9, 3.1, 4.9, 1.5, 1],
 [6.9, 3.2, 5.7, 2.3, 2],
 [6.5, 2.8, 4.6, 1.5, 1],
 [6.2, 2.8, 4.8, 1.8, 2],
 [6.7, 3.1, 5.6, 2.4, 2],
 [6.4, 2.8, 5.6, 2.2, 2],
 [6.4, 3.1, 5.5, 1.8, 2],
 [5.1, 3.5, 1.4, 0.3, 0],
 [7.7, 2.6, 6.9, 2.3, 2],
 [6.2, 2.9, 4.3, 1.3, 1],
 [5.7, 3.8, 1.7, 0.3, 0],
 [4.4, 3.0, 1.3, 0.2, 0],
 [6.6, 3.0, 4.4, 1.4, 1],
 [7.4, 2.8, 6.1, 1.9, 2],
 [5.0, 2.0, 3.5, 1.0, 1],
 [7.1, 3.0, 5.9, 2.1, 2],
 [5.5, 2.5, 4.0, 1.3, 1],
 [5.8, 2.7, 4.1, 1.0, 1],
 [6.1, 2.6, 5.6, 1.4, 2],
 [6.7, 2.5, 5.8, 1.8, 2],
 [6.7, 3.3, 5.7, 2.1, 2],
 [5.1, 3.8, 1.9, 0.4, 0],
 [5.6, 2.5, 3.9, 1.1, 1],
 [4.5, 2.3, 1.3, 0.3, 0],
 [6.1, 2.9, 4.7, 1.4, 1],
 [5.7, 2.8, 

In [17]:
k = 5

In [18]:
split_point = int((len(data_list) / k) * (k - 1))

data_train, data_test = data_list[:split_point], data_list[split_point:]

In [19]:
len(data_list)

150

In [20]:
len(data_train)

120

In [21]:
data_train

[[4.4, 2.9, 1.4, 0.2, 0],
 [6.4, 2.9, 4.3, 1.3, 1],
 [4.8, 3.1, 1.6, 0.2, 0],
 [6.3, 2.9, 5.6, 1.8, 2],
 [5.2, 3.5, 1.5, 0.2, 0],
 [6.1, 2.8, 4.7, 1.2, 1],
 [7.7, 3.0, 6.1, 2.3, 2],
 [6.2, 2.2, 4.5, 1.5, 1],
 [4.8, 3.4, 1.6, 0.2, 0],
 [6.3, 2.3, 4.4, 1.3, 1],
 [4.6, 3.1, 1.5, 0.2, 0],
 [6.2, 3.4, 5.4, 2.3, 2],
 [5.4, 3.7, 1.5, 0.2, 0],
 [6.9, 3.1, 4.9, 1.5, 1],
 [6.9, 3.2, 5.7, 2.3, 2],
 [6.5, 2.8, 4.6, 1.5, 1],
 [6.2, 2.8, 4.8, 1.8, 2],
 [6.7, 3.1, 5.6, 2.4, 2],
 [6.4, 2.8, 5.6, 2.2, 2],
 [6.4, 3.1, 5.5, 1.8, 2],
 [5.1, 3.5, 1.4, 0.3, 0],
 [7.7, 2.6, 6.9, 2.3, 2],
 [6.2, 2.9, 4.3, 1.3, 1],
 [5.7, 3.8, 1.7, 0.3, 0],
 [4.4, 3.0, 1.3, 0.2, 0],
 [6.6, 3.0, 4.4, 1.4, 1],
 [7.4, 2.8, 6.1, 1.9, 2],
 [5.0, 2.0, 3.5, 1.0, 1],
 [7.1, 3.0, 5.9, 2.1, 2],
 [5.5, 2.5, 4.0, 1.3, 1],
 [5.8, 2.7, 4.1, 1.0, 1],
 [6.1, 2.6, 5.6, 1.4, 2],
 [6.7, 2.5, 5.8, 1.8, 2],
 [6.7, 3.3, 5.7, 2.1, 2],
 [5.1, 3.8, 1.9, 0.4, 0],
 [5.6, 2.5, 3.9, 1.1, 1],
 [4.5, 2.3, 1.3, 0.3, 0],
 [6.1, 2.9, 4.7, 1.4, 1],
 [5.7, 2.8, 

In [22]:
len(data_test)

30

In [23]:
data_test

[[5.4, 3.0, 4.5, 1.5, 1],
 [6.8, 3.0, 5.5, 2.1, 2],
 [6.9, 3.1, 5.4, 2.1, 2],
 [6.9, 3.1, 5.1, 2.3, 2],
 [7.2, 3.6, 6.1, 2.5, 2],
 [6.0, 3.4, 4.5, 1.6, 1],
 [5.8, 2.7, 3.9, 1.2, 1],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.8, 3.0, 1.4, 0.3, 0],
 [5.5, 2.3, 4.0, 1.3, 1],
 [6.3, 2.5, 4.9, 1.5, 1],
 [5.6, 3.0, 4.1, 1.3, 1],
 [5.9, 3.2, 4.8, 1.8, 1],
 [4.6, 3.2, 1.4, 0.2, 0],
 [6.1, 2.8, 4.0, 1.3, 1],
 [7.7, 3.8, 6.7, 2.2, 2],
 [6.0, 2.2, 5.0, 1.5, 2],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.1, 2.5, 3.0, 1.1, 1],
 [5.8, 2.7, 5.1, 1.9, 2],
 [5.8, 2.8, 5.1, 2.4, 2],
 [5.1, 3.8, 1.5, 0.3, 0],
 [6.7, 3.1, 4.7, 1.5, 1],
 [5.6, 2.8, 4.9, 2.0, 2],
 [5.5, 2.6, 4.4, 1.2, 1],
 [6.0, 2.7, 5.1, 1.6, 1],
 [6.3, 3.3, 4.7, 1.6, 1],
 [4.9, 2.4, 3.3, 1.0, 1]]

In [24]:
data_train_in = []
data_train_out = []

for row in data_train:
    data_train_in.append([row[0], row[1], row[2], row[3]])
    data_train_out.append(row[4])
    
data_test_in = []
data_test_out = []

for row in data_test:
    data_test_in.append([row[0], row[1], row[2], row[3]])
    data_test_out.append(row[4])

In [25]:
data_train_in

[[4.4, 2.9, 1.4, 0.2],
 [6.4, 2.9, 4.3, 1.3],
 [4.8, 3.1, 1.6, 0.2],
 [6.3, 2.9, 5.6, 1.8],
 [5.2, 3.5, 1.5, 0.2],
 [6.1, 2.8, 4.7, 1.2],
 [7.7, 3.0, 6.1, 2.3],
 [6.2, 2.2, 4.5, 1.5],
 [4.8, 3.4, 1.6, 0.2],
 [6.3, 2.3, 4.4, 1.3],
 [4.6, 3.1, 1.5, 0.2],
 [6.2, 3.4, 5.4, 2.3],
 [5.4, 3.7, 1.5, 0.2],
 [6.9, 3.1, 4.9, 1.5],
 [6.9, 3.2, 5.7, 2.3],
 [6.5, 2.8, 4.6, 1.5],
 [6.2, 2.8, 4.8, 1.8],
 [6.7, 3.1, 5.6, 2.4],
 [6.4, 2.8, 5.6, 2.2],
 [6.4, 3.1, 5.5, 1.8],
 [5.1, 3.5, 1.4, 0.3],
 [7.7, 2.6, 6.9, 2.3],
 [6.2, 2.9, 4.3, 1.3],
 [5.7, 3.8, 1.7, 0.3],
 [4.4, 3.0, 1.3, 0.2],
 [6.6, 3.0, 4.4, 1.4],
 [7.4, 2.8, 6.1, 1.9],
 [5.0, 2.0, 3.5, 1.0],
 [7.1, 3.0, 5.9, 2.1],
 [5.5, 2.5, 4.0, 1.3],
 [5.8, 2.7, 4.1, 1.0],
 [6.1, 2.6, 5.6, 1.4],
 [6.7, 2.5, 5.8, 1.8],
 [6.7, 3.3, 5.7, 2.1],
 [5.1, 3.8, 1.9, 0.4],
 [5.6, 2.5, 3.9, 1.1],
 [4.5, 2.3, 1.3, 0.3],
 [6.1, 2.9, 4.7, 1.4],
 [5.7, 2.8, 4.1, 1.3],
 [5.6, 2.7, 4.2, 1.3],
 [6.5, 3.0, 5.8, 2.2],
 [4.9, 3.0, 1.4, 0.2],
 [5.0, 3.5, 1.3, 0.3],
 [5.7, 2.5,

In [26]:
data_train_out

[0,
 1,
 0,
 2,
 0,
 1,
 2,
 1,
 0,
 1,
 0,
 2,
 0,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 0,
 0,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 0,
 1,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 1,
 1,
 1,
 2,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 2,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 2,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 0,
 1,
 0,
 1]

In [27]:
data_test_in

[[5.4, 3.0, 4.5, 1.5],
 [6.8, 3.0, 5.5, 2.1],
 [6.9, 3.1, 5.4, 2.1],
 [6.9, 3.1, 5.1, 2.3],
 [7.2, 3.6, 6.1, 2.5],
 [6.0, 3.4, 4.5, 1.6],
 [5.8, 2.7, 3.9, 1.2],
 [5.1, 3.7, 1.5, 0.4],
 [4.9, 3.1, 1.5, 0.1],
 [4.8, 3.0, 1.4, 0.3],
 [5.5, 2.3, 4.0, 1.3],
 [6.3, 2.5, 4.9, 1.5],
 [5.6, 3.0, 4.1, 1.3],
 [5.9, 3.2, 4.8, 1.8],
 [4.6, 3.2, 1.4, 0.2],
 [6.1, 2.8, 4.0, 1.3],
 [7.7, 3.8, 6.7, 2.2],
 [6.0, 2.2, 5.0, 1.5],
 [5.1, 3.3, 1.7, 0.5],
 [4.8, 3.4, 1.9, 0.2],
 [5.1, 2.5, 3.0, 1.1],
 [5.8, 2.7, 5.1, 1.9],
 [5.8, 2.8, 5.1, 2.4],
 [5.1, 3.8, 1.5, 0.3],
 [6.7, 3.1, 4.7, 1.5],
 [5.6, 2.8, 4.9, 2.0],
 [5.5, 2.6, 4.4, 1.2],
 [6.0, 2.7, 5.1, 1.6],
 [6.3, 3.3, 4.7, 1.6],
 [4.9, 2.4, 3.3, 1.0]]

In [28]:
data_test_out

[1,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1]

In [29]:
number_of_clusters = 3
max_iteration = 100

In [30]:
fcm = FCM(n_clusters=number_of_clusters, 
          max_iter=max_iteration)

# Eğitim
fcm.fit(data_train_in, data_train_out)

In [31]:
prediction = fcm.predict(numpy.array(data_test_in))

In [32]:
prediction

array([[0.0373393 , 0.81636854, 0.14629215],
       [0.0023133 , 0.01845743, 0.97922927],
       [0.00611386, 0.0478383 , 0.94604784],
       [0.01683224, 0.13403702, 0.84913074],
       [0.03308559, 0.14829681, 0.8186176 ],
       [0.03497858, 0.73934828, 0.22567315],
       [0.0202413 , 0.9406914 , 0.0390673 ],
       [0.98442777, 0.01067899, 0.00489324],
       [0.98030465, 0.01362396, 0.00607139],
       [0.9685066 , 0.021725  , 0.0097684 ],
       [0.04772692, 0.85845042, 0.09382267],
       [0.02349593, 0.60990613, 0.36659794],
       [0.02524131, 0.91542231, 0.05933638],
       [0.0310732 , 0.59245733, 0.37646947],
       [0.97118563, 0.01968934, 0.00912503],
       [0.0082293 , 0.96862991, 0.02314079],
       [0.05987362, 0.21439317, 0.72573321],
       [0.03297678, 0.61024926, 0.35677396],
       [0.97407801, 0.01826241, 0.00765958],
       [0.95949334, 0.02843593, 0.01207073],
       [0.32974586, 0.53702221, 0.13323194],
       [0.02900323, 0.44744242, 0.52355434],
       [0.

In [33]:
max_of_predictions = numpy.argmax(prediction, 
                                  axis=1)
max_of_predictions

array([1, 2, 2, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 2,
       2, 0, 1, 1, 1, 1, 1, 1])

In [34]:
from sklearn.metrics import accuracy_score

accuracy_score(data_test_out, max_of_predictions)

0.9333333333333333

In [35]:
max_of_predictions

array([1, 2, 2, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 2,
       2, 0, 1, 1, 1, 1, 1, 1])

In [36]:
data_test_out

[1,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1]

In [37]:
dummy = []

for x in range(len(max_of_predictions)):
    dummy.append(random.choice([0, 1, 2]))

In [38]:
accuracy_score(data_test_out, dummy)

0.3333333333333333

Çapraz Geçerleme

In [39]:
from sklearn.model_selection import KFold

splitter = KFold(n_splits=k)

split_indexes = []
for fold_id, (train_index, test_index) in enumerate(splitter.split(data_list)):
    print("Train" + str(train_index))
    print("Test" + str(test_index))

Train[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
Test[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Train[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129

In [40]:
def get_data(complete_data, 
             train_indexes, 
             test_indexes):
    train_data_in = []
    train_data_out = []
    for x in train_indexes:
        train_data = complete_data[x]
        train_data_in.append([train_data[0], train_data[1], train_data[2], train_data[3]])
        train_data_out.append(train_data[4])
    test_data_in = []
    test_data_out = []
    for x in test_indexes:
        test_data = complete_data[x]
        test_data_in.append([test_data[0], test_data[1], test_data[2], test_data[3]])
        test_data_out.append(test_data[4])
    return train_data_in, train_data_out, test_data_in, test_data_out

In [41]:
number_of_clusters = 3
max_iteration = 100

In [42]:
for fold_id, (train_index, test_index) in enumerate(splitter.split(data_list)):
    train_data_in, train_data_out, test_data_in, test_data_out = get_data(data_list,
                                                                          train_index,
                                                                          test_index)
    if fold_id == 0:
        print(test_data_in)

[[4.4, 2.9, 1.4, 0.2], [6.4, 2.9, 4.3, 1.3], [4.8, 3.1, 1.6, 0.2], [6.3, 2.9, 5.6, 1.8], [5.2, 3.5, 1.5, 0.2], [6.1, 2.8, 4.7, 1.2], [7.7, 3.0, 6.1, 2.3], [6.2, 2.2, 4.5, 1.5], [4.8, 3.4, 1.6, 0.2], [6.3, 2.3, 4.4, 1.3], [4.6, 3.1, 1.5, 0.2], [6.2, 3.4, 5.4, 2.3], [5.4, 3.7, 1.5, 0.2], [6.9, 3.1, 4.9, 1.5], [6.9, 3.2, 5.7, 2.3], [6.5, 2.8, 4.6, 1.5], [6.2, 2.8, 4.8, 1.8], [6.7, 3.1, 5.6, 2.4], [6.4, 2.8, 5.6, 2.2], [6.4, 3.1, 5.5, 1.8], [5.1, 3.5, 1.4, 0.3], [7.7, 2.6, 6.9, 2.3], [6.2, 2.9, 4.3, 1.3], [5.7, 3.8, 1.7, 0.3], [4.4, 3.0, 1.3, 0.2], [6.6, 3.0, 4.4, 1.4], [7.4, 2.8, 6.1, 1.9], [5.0, 2.0, 3.5, 1.0], [7.1, 3.0, 5.9, 2.1], [5.5, 2.5, 4.0, 1.3]]


In [43]:
accs = []

for fold_id, (train_index, test_index) in enumerate(splitter.split(data_list)):
    train_data_in, train_data_out, test_data_in, test_data_out = get_data(data_list,
                                                                          train_index,
                                                                          test_index)
    fcm_model = FCM(n_clusters=number_of_clusters,
                    max_iter=max_iteration)
    fcm_model.fit(train_data_in, train_data_out)
    predicted = numpy.argmax(fcm_model.predict(numpy.array(test_data_in)), 
                             axis=1)
    real = numpy.array(test_data_out)
    print(real)
    print(predicted)
    score = accuracy_score(real,
                                    predicted)
    print("Accuracy of Fold " + str(fold_id) + ": " + str(score))
    accs.append(score)


[0 1 0 2 0 1 2 1 0 1 0 2 0 1 2 1 2 2 2 2 0 2 1 0 0 1 2 1 2 1]
[0 1 0 2 0 1 2 1 0 1 0 2 0 2 2 1 1 2 2 2 0 2 1 0 0 1 2 1 2 1]
Accuracy of Fold 0: 0.9333333333333333
[1 2 2 2 0 1 0 1 1 1 2 0 0 2 1 0 0 1 1 0 2 2 0 0 0 1 2 0 2 1]
[1 2 2 2 0 1 0 1 1 1 2 0 0 1 1 0 0 1 1 0 2 1 0 0 0 1 1 0 2 2]
Accuracy of Fold 1: 0.8666666666666667
[0 2 0 1 0 1 2 0 2 2 2 0 0 2 1 1 1 2 2 0 0 1 1 2 1 0 0 2 2 2]
[0 2 0 2 0 1 2 0 2 1 2 0 0 2 1 1 1 2 2 0 0 1 1 2 1 0 0 2 2 2]
Accuracy of Fold 2: 0.9333333333333333
[2 1 2 0 1 0 0 0 2 1 0 0 2 0 0 2 0 1 2 0 1 0 2 1 2 2 0 1 0 1]
[2 1 2 0 1 0 0 0 2 1 0 0 2 0 0 2 0 1 2 0 1 0 2 1 2 2 0 1 0 1]
Accuracy of Fold 3: 1.0
[1 2 2 2 2 1 1 0 0 0 1 1 1 1 0 1 2 2 0 0 1 2 2 0 1 2 1 1 1 1]
[1 2 2 2 2 1 1 0 0 0 1 1 1 1 0 1 2 1 0 0 1 2 2 0 1 1 1 1 1 1]
Accuracy of Fold 4: 0.9333333333333333


In [44]:
print("Avg Accuracy: " + str(sum(accs) / len(accs)))

Avg Accuracy: 0.9333333333333333
